# Generated by Django 4.0.5 on 2022-07-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido',
            new_name='contraseña',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
    ]
