# Generated by Django 4.0.5 on 2022-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_apellido_empleado_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horario',
            field=models.CharField(max_length=50),
        ),
    ]
