# Generated by Django 4.0.5 on 2022-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registro_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Registro',
            new_name='Registro_Egreso',
        ),
    ]
