# Generated by Django 4.0.5 on 2022-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registro_ingreso_rename_registro_registro_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_egreso',
            name='fecha',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
