# Generated by Django 4.0.5 on 2022-07-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registro_egreso_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_ingreso',
            name='fecha',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
